<?php
/**
 * unit-gdpr:/index.phtml
 *
 * @creation  2018-11-15
 * @version   1.0
 * @package   unit-gdpr
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="GDPR" class="GDPR">
	<div class="close"></div>
	We use cookies to make interactions with our websites and services easy and meaningful,
	to better understand how they are used and to tailor advertising.
	You can <a href="https://www.salesforce.com/company/privacy/full_privacy.jsp#nav_info">read more</a>
	and
	<a href="https://www.salesforce.com/company/privacy/full_privacy.jsp#nav_info">make your cookie choices here</a>.
	By continuing to use this site you are giving us your consent to do this.
</section>
